//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string MaLuong { get; set; }
        public Nullable<double> LuongChinh { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public Nullable<int> SoNgayDiLam { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public Nullable<double> TienThuong { get; set; }
        public Nullable<double> TienPhat { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
