//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongNV
    {
        public string MaDA { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> ThoiGianStart { get; set; }
        public Nullable<System.DateTime> ThoiGianEnd { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
